In [1]:
import open3d as o3d
import numpy as np
import os
import sys

sys.path.append('..')

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [3]:
pcd = o3d.io.read_point_cloud("test.ply")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 307199 points.
[[-9.71566445e-05  7.28294721e-05 -1.59647068e-04]
 [-9.68525548e-05  7.28294721e-05 -1.59647068e-04]
 [-9.65484651e-05  7.28294721e-05 -1.59647068e-04]
 ...
 [ 2.14002702e-04 -1.61428810e-04 -3.53862735e-04]
 [ 2.14676726e-04 -1.61428810e-04 -3.53862735e-04]
 [ 2.15350750e-04 -1.61428810e-04 -3.53862735e-04]]


In [2]:
dataset = o3d.data.EaglePointCloud()
pcd = o3d.io.read_point_cloud(dataset.path)
o3d.visualization.draw(pcd)

2024-07-28 17:40:05.388 Python[33879:538547] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/cs/0p38q9jj01q8230vr6wgk1dr0000gn/T/com.apple.python3.savedState
[error] GLFW error: Cocoa: Failed to find service port for display


FEngine (64 bits) created at 0x31a698000 (threading is enabled)
FEngine resolved backend: OpenGL
