In [1]:
import open3d as o3d
import numpy as np
import os
import sys

sys.path.append('..')

In [2]:
pcd = o3d.io.read_point_cloud("Buggy.ply")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 4482701 points.
[[  329.08828735    23.08819962   739.94317627]
 [  332.5519104     23.97890091   738.54797363]
 [  332.60549927    22.58480072   738.39868164]
 ...
 [-1083.25488281  -479.74758911  -250.69039917]
 [-1085.24255371  -479.3788147   -248.79150391]
 [-1086.08117676  -478.66110229  -247.2671051 ]]
[Open3D WARNING] GLFW Error: Cocoa: Failed to find service port for display


2024-07-28 17:39:19.915 Python[30545:492016] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/cs/0p38q9jj01q8230vr6wgk1dr0000gn/T/com.apple.python3.savedState
2024-07-28 17:39:32.151 Python[30545:492016] WARNING: Secure coding is automatically enabled for restorable state! However, not on all supported macOS versions of this application. Opt-in to secure coding explicitly by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState:.


In [2]:
dataset = o3d.data.EaglePointCloud()
pcd = o3d.io.read_point_cloud(dataset.path)
o3d.visualization.draw(pcd)

2024-07-28 17:40:05.388 Python[33879:538547] ApplePersistenceIgnoreState: Existing state will not be touched. New state will be written to /var/folders/cs/0p38q9jj01q8230vr6wgk1dr0000gn/T/com.apple.python3.savedState
[error] GLFW error: Cocoa: Failed to find service port for display


FEngine (64 bits) created at 0x31a698000 (threading is enabled)
FEngine resolved backend: OpenGL
